use anyhow::{bail, Result};
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::{log, ui};

const ZINIT_REPO: &str = "https://github.com/zdharma-continuum/zinit.git";

const ZSHRC_CONTENT: &str = r#"# Caelestia Zsh Configuration
# Generated by caelestia-installer

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# Basic options
setopt AUTO_CD
setopt INTERACTIVE_COMMENTS
setopt NO_BEEP

# Completion
autoload -Uz compinit
compinit

# Zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"

# Plugins
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-history-substring-search

# Key bindings for history search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# zoxide (smart cd)
eval "$(zoxide init zsh)"

# fzf key bindings and completion
if [[ -f /usr/share/fzf/shell/key-bindings.zsh ]]; then
    source /usr/share/fzf/shell/key-bindings.zsh
fi

# Starship prompt
eval "$(starship init zsh)"

# Aliases
alias ls='ls --color=auto'
alias ll='ls -la'
alias la='ls -A'
alias grep='grep --color=auto'
alias cd='z'
alias zz='z -'

# Hyprland environment
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    export XDG_CURRENT_DESKTOP=Hyprland
    export XDG_SESSION_DESKTOP=Hyprland
    export XDG_SESSION_TYPE=wayland
fi
"#;

pub fn setup_all(dry_run: bool) -> Result<()> {
    install_zinit(dry_run)?;
    write_zshrc(dry_run)?;
    set_default_shell(dry_run)?;
    Ok(())
}

fn install_zinit(dry_run: bool) -> Result<()> {
    let data_dir = dirs::data_local_dir().unwrap_or_else(|| PathBuf::from("~/.local/share"));
    let zinit_dir = data_dir.join("zinit/zinit.git");

    ui::info("Installing Zinit plugin manager...");

    if dry_run {
        ui::success("Would install Zinit (dry-run)");
        return Ok(());
    }

    if zinit_dir.exists() {
        ui::success("Zinit already installed");
        return Ok(());
    }

    if let Some(parent) = zinit_dir.parent() {
        fs::create_dir_all(parent)?;
    }

    let cmd = format!("git clone {} {:?}", ZINIT_REPO, zinit_dir);
    log::log_command(&cmd);

    let output = Command::new("git")
        .args(["clone", ZINIT_REPO, zinit_dir.to_str().unwrap()])
        .output()?;

    if output.status.success() {
        ui::success("Zinit installed");
        log::log("Zinit installation complete");
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        log::log_error(&stderr);
        bail!("Failed to install Zinit");
    }
}

fn write_zshrc(dry_run: bool) -> Result<()> {
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("~"));
    let zshrc_path = home.join(".zshrc");

    ui::info("Writing .zshrc configuration...");

    if dry_run {
        ui::success("Would write .zshrc (dry-run)");
        return Ok(());
    }

    // Backup existing .zshrc
    if zshrc_path.exists() {
        let backup_path = home.join(".zshrc.bak");
        ui::warning(&format!("Backing up existing .zshrc to {:?}", backup_path));
        fs::copy(&zshrc_path, &backup_path)?;
    }

    fs::write(&zshrc_path, ZSHRC_CONTENT)?;
    ui::success("Wrote .zshrc");
    log::log("Created .zshrc configuration");

    Ok(())
}

fn set_default_shell(dry_run: bool) -> Result<()> {
    ui::info("Setting zsh as default shell...");

    if dry_run {
        ui::success("Would set zsh as default shell (dry-run)");
        return Ok(());
    }

    let cmd = "chsh -s /bin/zsh";
    log::log_command(cmd);

    let output = Command::new("chsh").args(["-s", "/bin/zsh"]).status();

    match output {
        Ok(s) if s.success() => {
            ui::success("Set zsh as default shell");
            log::log("Default shell changed to zsh");
            Ok(())
        }
        Ok(_) => {
            ui::warning("Could not set default shell (may need to run manually: chsh -s /bin/zsh)");
            Ok(())
        }
        Err(e) => {
            log::log_error(&format!("chsh failed: {}", e));
            ui::warning("Could not set default shell");
            Ok(())
        }
    }
}
